Added some helpers for string manipulation.
mockoon/commons pull request #19
Opened 2021-02-04 17:07 UTC by SimonPStevens

**Parent issue** 

Closes https://github.com/mockoon/mockoon/issues/413

**Technical implementation details**

Added some string manipulation helpers that just call the equivalent Javascript methods directly.

2021-02-08 08:44 UTC, 255kb commented
Thank you @SimonPStevens for these helpers :) 
Like for the `dateTimeShift` helper, you should account for the case where no params are passed. We currently have an error with the `indexOf` (didn't test the other helpers) when used like this: `{{indexOf}}`. 
Could you please also add more test cases? Like for the `setVar`: one case without param, with only the first param, with string param, number param, another embedded helper (`indexOf (body 'prop') 'a'`), etc. Helpers code is a little bit easy to break and I want it to be covered as much as possible. 
Thanks!

2021-02-09 09:50 UTC, SimonPStevens commented
Yeah, no prob. I'll get to this later in the week.

2021-03-08 17:06 UTC, SimonPStevens commented
Hey. Sorry it took me way longer than I said to get round to doing this. I've added some more unit tests, and fixed the error when the wrong parameter type is passed. Let me know if there is anything else that needs doing.

2021-03-08 17:14 UTC, SimonPStevens commented
Actually. Hold off. This still doesn't work with variables, and I'm not quite sure why. I'm still working on it.

2021-03-08 21:53 UTC, SimonPStevens commented
OK. I think this is good now.

That opened up a bit of a can of worms with the different parameter types that can be passed to the helpers. I've covered everything I can think of now, but if you can see anything I've missed then let me know.

2021-03-12 09:30 UTC, 255kb requested changes

2021-03-12 09:30 UTC, 255kb commented on src/libs/template-parser.ts
> +        return data.toString().indexOf(search.toString(), position);
`data` and `search` are already converted to string above
```suggestion
        return data.indexOf(search, position);
```

2021-03-12 09:30 UTC, 255kb commented on src/libs/template-parser.ts
> +        return data.toString().indexOf(search.toString());
`data` and `search` are already converted to string above
```suggestion
        return data.indexOf(search);
```

2021-03-12 09:30 UTC, 255kb commented on src/libs/template-parser.ts
> +      return data.toString().includes(search.toString());
`data` and `search` are already converted to string above
```suggestion
      return data.includes(search);
```

2021-03-12 09:31 UTC, 255kb commented
@SimonPStevens It looks good. Just 3 `toString()` that seems redundant to me. Then it's ready to be merged!

2021-03-12 14:34 UTC, SimonPStevens commented
@255kb All done.

2021-03-12 14:34 UTC, 255kb commented
Thanks @SimonPStevens !

2021-03-12 14:37 UTC, 255kb approved these changes

2021-03-12 14:38 UTC, merged